name: build-macosx-amd64

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Git repository to clone'
        required: true
        default: 'https://github.com/ansorre/java-cef.git'
      ref:
        description: 'Git commit id to checkout'
        required: true
        default: 'master'

jobs:
  build-macosx-amd64:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      -
        name: Setup environment
        run: |
          chmod +x scripts/install_macos_dependencies.sh
          ./scripts/install_macos_dependencies.sh
      -
        name: Build
        run: |
          chmod +x compile_macosx.sh
          ./compile_macosx.sh amd64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      -
        name: Export artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macosx-amd64.tar.gz
          path: out/binary_distrib.tar.gz

